version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./database.db:/app/database.db
    env_file:
      - .env
    restart: unless-stopped 